name: Static Checking

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  staticCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ^14.0.0
      - name: Install Dependencies
        run: bahmutov/npm-install@v1.7.7
      - name: Run Stactic Check
        run: npm run static-check
